version: '3.1'
volumes:
  data:
  capnp-secrets:
secrets:
  ocaml-ci-github-key:
    external: true
  ocaml-ci-oauth:
    external: true
  ocaml-ci-submission.cap:
    external: true
  matrix-pass:
    external: true
  ocaml-ci-webhook-secret:
    external: true
services:
  ci:
    image: ocurrent/ocaml-ci-service:live
    command: --github-app-id 39151 --github-private-key-file /run/secrets/ocaml-ci-github-key --github-account-allowlist "talex5,ocurrent,ocaml,mirage,avsm,samoht,kit-ty-kate,tarides,aantron,ocamllabs,realworldocaml,NathanReb,0install,gpetiot,ocaml-ppx,CraigFe,pascutto,julow,ocaml-gospel,vbmithr,gs0510,magnuss,dune-universe,janestreet,emillon,capnproto,ocaml-opam,ocaml-dune,favonia,joelburget,jeffa5,bikallem,jonludlam,g2p,stedolan,ocsigen,dinosaure,hannesm,mirleft,roburio,misterda,ocaml-multicore,cdaringe,inhabitedtype,tmcgilchrist,ocaml-doc,grievejia,Leonidas-from-XIV" --confirm above-average --confirm-auto-release 120 --capnp-address=tcp:ci.ocamllabs.io:8102 --github-oauth /run/secrets/ocaml-ci-oauth --submission-service /run/secrets/ocaml-ci-submission.cap --matrix-passfile /run/secrets/matrix-pass --matrix-user ocaml-ci --matrix-host=matrix.ocamllabs.io --github-webhook-secret-file /run/secrets/ocaml-ci-webhook-secret
    environment:
      - "CI_PROFILE=production"
      - "DOCKER_BUILDKIT=1"
      - "PROGRESS_NO_TRUNC=1"
    ports:
      - '8102:9000'
    volumes:
      - 'data:/var/lib/ocurrent'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'capnp-secrets:/capnp-secrets'
    secrets:
      - 'ocaml-ci-oauth'
      - 'ocaml-ci-github-key'
      - 'ocaml-ci-submission.cap'
      - 'matrix-pass'
      - 'ocaml-ci-webhook-secret'
    sysctls:
      - 'net.ipv4.tcp_keepalive_time=60'
  web:
    image: ocurrent/ocaml-ci-web:live
    command: --backend /capnp-secrets/ocaml-ci-admin.cap --listen-prometheus=9090
    volumes:
      - 'capnp-secrets:/capnp-secrets:ro'
    sysctls:
      - 'net.ipv4.tcp_keepalive_time=60'
